//! MVT decode fidelity (IO-10, super-band B3). Fixtures are hand-built
//! protobuf-wire bytes (generated by a standalone spec-v2.1 encoder), embedded
//! as constants — no external file dependency, deterministic by construction.

#![allow(clippy::float_cmp)]

use visiaengine_io_tiles::{MvtError, MvtValue, decode_tile};

/// Local varint encoder (mirror of the fixture generator script).
fn to_varint(mut v: u64) -> Vec<u8> {
    let mut out = Vec::new();
    loop {
        let b = (v & 0x7F) as u8;
        v >>= 7;
        if v == 0 {
            out.push(b);
            break;
        }
        out.push(b | 0x80);
    }
    out
}

// Fixture A: layer "road", 1 LineString (0,0)->(100,0)->(100,100), key "class"=str "highway".
const FIXTURE_A: &[u8] = &[
    26, 51, 10, 4, 114, 111, 97, 100, 18, 20, 8, 1, 24, 2, 18, 2, 0, 0, 34, 10, 9, 0, 0, 18, 200,
    1, 0, 0, 200, 1, 26, 5, 99, 108, 97, 115, 115, 34, 9, 10, 7, 104, 105, 103, 104, 119, 97, 121,
    40, 128, 32, 48, 2,
];
// Fixture B: layer "poi" (point id=7, tag pairs name=tower rank=42; open value unused; extent 4096)
//            + layer "land" (polygon ring full-tile, kind=area).
const FIXTURE_B: &[u8] = &[
    26, 64, 10, 3, 112, 111, 105, 18, 17, 8, 7, 24, 1, 18, 4, 0, 0, 1, 1, 34, 5, 9, 128, 32, 128,
    16, 26, 4, 110, 97, 109, 101, 26, 4, 114, 97, 110, 107, 26, 4, 111, 112, 101, 110, 34, 7, 10,
    5, 116, 111, 119, 101, 114, 34, 2, 32, 42, 34, 2, 56, 1, 40, 128, 32, 48, 2, 26, 51, 10, 4,
    108, 97, 110, 100, 18, 24, 8, 8, 24, 3, 18, 2, 0, 0, 34, 14, 9, 0, 0, 26, 128, 64, 0, 0, 128,
    64, 255, 63, 0, 15, 26, 4, 107, 105, 110, 100, 34, 6, 10, 4, 97, 114, 101, 97, 40, 128, 32, 48,
    2,
];
// Fixture C: A truncated by 5 bytes (mid-geometry).
const FIXTURE_C: &[u8] = &[
    26, 51, 10, 4, 114, 111, 97, 100, 18, 20, 8, 1, 24, 2, 18, 2, 0, 0, 34, 10, 9, 0, 0, 18, 200,
    1, 0, 0, 200, 1, 26, 5, 99, 108, 97, 115, 115, 34, 9, 10, 7, 104, 105, 103, 104, 119, 97, 121,
];
// Fixture D: layer version=1 (unsupported).
const FIXTURE_D: &[u8] = &[
    26, 20, 10, 2, 118, 49, 18, 9, 8, 1, 24, 1, 34, 3, 9, 0, 0, 40, 128, 32, 48, 1,
];

// spec: IO-10
#[test]
fn fixture_a_line_layer_decodes() {
    let tile = decode_tile(FIXTURE_A).expect("A decodes");
    assert_eq!(tile.layers.len(), 1);
    let layer = &tile.layers[0];
    assert_eq!(layer.name, "road");
    assert_eq!(layer.extent, 4096);
    assert_eq!(layer.version, 2);
    assert_eq!(layer.features.len(), 1);
    let f = &layer.features[0];
    assert_eq!(f.id, 1);
    assert_eq!(f.geom_type(), 2, "LineString");
    assert_eq!(
        f.tags(layer).get("class"),
        Some(&MvtValue::Str("highway".into()))
    );
    assert_eq!(
        f.commands,
        vec![(1, 1), (2, 2)],
        "MoveTo(1) + LineTo(2) command words"
    );
    assert_eq!(f.points.len(), 3, "three vertices");
    assert_eq!(f.points[2], (100, 100), "absolute endpoint after deltas");
}

// spec: IO-10
#[test]
fn fixture_b_multilayer_values_decode() {
    let tile = decode_tile(FIXTURE_B).expect("B decodes");
    assert_eq!(tile.layers.len(), 2);
    let poi = &tile.layers[0];
    assert_eq!(poi.name, "poi");
    let f = &poi.features[0];
    assert_eq!(f.geom_type(), 1, "POINT");
    assert_eq!(
        f.tags(poi).get("name"),
        Some(&MvtValue::Str("tower".into()))
    );
    assert_eq!(f.tags(poi).get("rank"), Some(&MvtValue::Int(42)));
    assert_eq!(
        f.tags(poi).get("open"),
        None,
        "open unpaired in fixture (values[2] unused)"
    );
    assert_eq!(f.points, vec![(2048, 1024)]);
    let land = &tile.layers[1];
    let g = &land.features[0];
    assert_eq!(g.geom_type(), 3, "POLYGON");
    // ring: MoveTo(1) + LineTo(3) = 4 explicit points; ClosePath returns to the
    // ring start IMPLICITLY (spec: no extra coordinate word for the closure).
    assert_eq!(g.points.len(), 4);
    assert!(g.closed, "polygon ring closed");
    assert_eq!(g.points[0], (0, 0), "ring starts at fixture origin");
}

// spec: IO-10
#[test]
fn truncated_input_is_typed_error() {
    match decode_tile(FIXTURE_C) {
        Err(MvtError::Truncated) => {}
        other => panic!("expected Truncated, got {other:?}"),
    }
}

// spec: IO-10
#[test]
fn unsupported_version_rejected() {
    match decode_tile(FIXTURE_D) {
        Err(MvtError::UnsupportedVersion(1)) => {}
        other => panic!("expected UnsupportedVersion(1), got {other:?}"),
    }
}

// spec: IO-10
#[test]
fn empty_input_truncated() {
    assert!(matches!(decode_tile(&[]), Err(MvtError::Truncated)));
}

// spec: IO-10
#[test]
fn zigzag_roundtrip_negative_deltas() {
    // Negative deltas must survive zigzag: build a 2-point line going left/up.
    // Reuse fixture A shape but hand-assemble: MoveTo(10,10) LineTo(-30,-40).
    // Rather than re-encode, assert fixture A's known positive deltas decode and
    // rely on the encoder-side negative coverage in fixture B polygon (0..4096).
    // Direct negative-delta fixture:
    //   geometry: cmd MoveTo(1) + zz(10) + zz(10), cmd LineTo(1) + zz(-30) + zz(-40)
    let geom: Vec<u8> = vec![9, 20, 20, 10, 59, 79];
    // wire: feature(type=2 LINE, geometry) + layer(name "neg", extent 4096, version 2)
    let mut feat = vec![24, 2, 34];
    feat.extend(to_varint(geom.len() as u64));
    feat.extend_from_slice(&geom);
    let mut layer = vec![10, 3, b'n', b'e', b'g'];
    layer.push(18);
    layer.extend(to_varint(feat.len() as u64));
    layer.extend_from_slice(&feat);
    layer.extend_from_slice(&[40, 128, 32, 48, 2]);
    let mut tile_bytes = vec![26];
    tile_bytes.extend(to_varint(layer.len() as u64));
    tile_bytes.extend_from_slice(&layer);

    let t = decode_tile(&tile_bytes).expect("neg fixture decodes");
    let pts = &t.layers[0].features[0].points;
    assert_eq!(pts[0], (10, 10));
    assert_eq!(pts[1], (10 - 30, 10 - 40), "negative deltas applied");
}
