# SDK 三级解析（§2.2）：AUTO|PIXI|SYSTEM|<显式路径>；负路径全部硬报错且报文指名补救动作。
# 依据 docs/reference/cmake-integration-patterns.md（iceoryx2 形改道：PATH 假定→三级解析）。

set(VISIAENGINE_RUST_SDK "AUTO" CACHE STRING "Rust 工具链：AUTO|PIXI|SYSTEM|<cargo 绝对路径>")
set(VISIAENGINE_QT_SDK "AUTO" CACHE STRING "Qt6：AUTO|PIXI|SYSTEM|OFF|<Qt6 前缀目录>")
set(VISIAENGINE_PIXI_ENV "qt-spike" CACHE STRING "pixi 环境名（该 env 目录缺位时回落 default）")
set(VISIAENGINE_ARTIFACT_PATH "" CACHE PATH "预构建 capi 产物目录（设之=纯消费，cargo 步不生成；文件缺失=硬错）")
set_property(CACHE VISIAENGINE_RUST_SDK PROPERTY STRINGS AUTO PIXI SYSTEM)
set_property(CACHE VISIAENGINE_QT_SDK PROPERTY STRINGS AUTO PIXI SYSTEM OFF)

# pixi 前缀发现：激活态 $CONDA_PREFIX 优先，否则仓内 .pixi/envs/<env>（gate-abi 同族惯例）
function(_ve_pixi_prefix out)
  if(DEFINED ENV{CONDA_PREFIX} AND EXISTS "$ENV{CONDA_PREFIX}/bin/cargo")
    set(${out} "$ENV{CONDA_PREFIX}" PARENT_SCOPE)
    return()
  endif()
  foreach(_env ${VISIAENGINE_PIXI_ENV} default)
    if(EXISTS "${CMAKE_SOURCE_DIR}/.pixi/envs/${_env}/bin/cargo")
      set(${out} "${CMAKE_SOURCE_DIR}/.pixi/envs/${_env}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${out} "" PARENT_SCOPE)
endfunction()

function(_ve_msrv_check cargo_path rust_version)
  execute_process(COMMAND "${cargo_path}" --version
                  OUTPUT_VARIABLE _out OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  if(_out MATCHES "([0-9]+)\\.([0-9]+)\\.([0-9]+)")
    set(_v "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}.${CMAKE_MATCH_3}")
    if(_v VERSION_LESS rust_version)
      message(WARNING "解析到 cargo ${_v} < workspace rust-version ${rust_version}（MSRV 合同；升 pixi 环境或换 SDK）")
    endif()
  endif()
endfunction()

function(visiaengine_resolve_sdks)
  _ve_pixi_prefix(_pixi)
  file(READ "${CMAKE_SOURCE_DIR}/Cargo.toml" _ws)
  string(REGEX MATCH "rust-version = \"([0-9.]+)\"" _rm "${_ws}")
  set(_msrv "${CMAKE_MATCH_1}")

  # ---- Rust / cargo（或纯消费产物模式）----
  if(VISIAENGINE_ARTIFACT_PATH)
    set(_so "${VISIAENGINE_ARTIFACT_PATH}/libvisiaengine.so")
    if(NOT EXISTS "${_so}" AND WIN32)
      set(_so "${VISIAENGINE_ARTIFACT_PATH}/visiaengine.dll")
    endif()
    if(NOT EXISTS "${_so}")
      message(FATAL_ERROR "VISIAENGINE_ARTIFACT_PATH=${VISIAENGINE_ARTIFACT_PATH} 无 capi 产物（逃生舱不静默消费旧物）")
    endif()
    set(VISIAENGINE_CARGO "" CACHE INTERNAL "prebuilt 模式无 cargo")
    set(VISIAENGINE_RUST_KIND "prebuilt" PARENT_SCOPE)
    message(STATUS "Rust SDK: prebuilt @ ${VISIAENGINE_ARTIFACT_PATH}")
  else()
    set(_cargo "")
    set(_kind "")
    if(VISIAENGINE_RUST_SDK STREQUAL "AUTO")
      if(_pixi AND EXISTS "${_pixi}/bin/cargo")
        set(_cargo "${_pixi}/bin/cargo")
        set(_kind "pixi")
      else()
        find_program(_found_cargo cargo)
        if(_found_cargo)
          set(_cargo "${_found_cargo}")
          set(_kind "system")
        endif()
      endif()
      if(NOT _cargo)
        message(FATAL_ERROR "AUTO 未找到 cargo：pixi 环境缺位（先跑 pixi install -e ${VISIAENGINE_PIXI_ENV}）且系统 PATH 无 cargo")
      endif()
    elseif(VISIAENGINE_RUST_SDK STREQUAL "PIXI")
      if(NOT _pixi OR NOT EXISTS "${_pixi}/bin/cargo")
        message(FATAL_ERROR "强制 PIXI 但 pixi 环境缺位：跑 pixi install -e ${VISIAENGINE_PIXI_ENV}（不回落系统）")
      endif()
      set(_cargo "${_pixi}/bin/cargo")
      set(_kind "pixi")
    elseif(VISIAENGINE_RUST_SDK STREQUAL "SYSTEM")
      find_program(_found_cargo cargo)
      if(NOT _found_cargo)
        message(FATAL_ERROR "强制 SYSTEM 但系统 PATH 无 cargo（不回落 pixi；改 PIXI 或给路径）")
      endif()
      # 反污染：pixi 激活把 conda cargo 塞进 PATH——SYSTEM 语义须真·系统工具链
      if((_pixi AND _found_cargo MATCHES "^${_pixi}/") OR
         (DEFINED ENV{CONDA_PREFIX} AND _found_cargo MATCHES "^$ENV{CONDA_PREFIX}/"))
        message(FATAL_ERROR "SYSTEM 模式拒收 pixi 激活 PATH 的 cargo（${_found_cargo}）；改 PIXI 或开未激活 shell")
      endif()
      set(_cargo "${_found_cargo}")
      set(_kind "system")
    else()
      if(NOT EXISTS "${VISIAENGINE_RUST_SDK}")
        message(FATAL_ERROR "VISIAENGINE_RUST_SDK=${VISIAENGINE_RUST_SDK} 不是可执行文件（显式路径=逃生舱，不存在即错）")
      endif()
      set(_cargo "${VISIAENGINE_RUST_SDK}")
      set(_kind "path")
    endif()
    _ve_msrv_check("${_cargo}" "${_msrv}")
    set(VISIAENGINE_CARGO "${_cargo}" CACHE INTERNAL "resolved cargo")
    set(VISIAENGINE_PIXI_PREFIX "${_pixi}" CACHE INTERNAL "resolved pixi prefix")
    set(VISIAENGINE_RUST_KIND "${_kind}" PARENT_SCOPE)
    message(STATUS "Rust SDK: ${_cargo} [${_kind}] · MSRV ${_msrv}")
  endif()

  # ---- Qt6 ----
  if(VISIAENGINE_QT_SDK STREQUAL "OFF")
    set(VISIAENGINE_QT_KIND "OFF" PARENT_SCOPE)
    message(STATUS "Qt: OFF（bare/cargo-only 配置态）")
    return()
  endif()
  set(_qkind "")
  if(VISIAENGINE_QT_SDK STREQUAL "AUTO")
    find_package(Qt6 COMPONENTS Widgets QUIET)
    if(Qt6_FOUND)
      set(_qkind "system")
    elseif(_pixi)
      list(APPEND CMAKE_PREFIX_PATH "${_pixi}")
      find_package(Qt6 COMPONENTS Widgets QUIET)
      if(Qt6_FOUND)
        set(_qkind "pixi")
      endif()
    endif()
    if(NOT Qt6_FOUND)
      message(STATUS "Qt: AUTO 双路未命中（系统/pixi）——Qt 消费者功能将不可用；跑 pixi install -e ${VISIAENGINE_PIXI_ENV} 或 -DVISIAENGINE_QT_SDK=<dir>")
    endif()
  elseif(VISIAENGINE_QT_SDK STREQUAL "PIXI" OR VISIAENGINE_QT_SDK STREQUAL "SYSTEM")
    if(VISIAENGINE_QT_SDK STREQUAL "PIXI")
      if(NOT _pixi)
        message(FATAL_ERROR "强制 PIXI 但无 pixi 环境：跑 pixi install -e ${VISIAENGINE_PIXI_ENV}（不回落系统）")
      endif()
      list(APPEND CMAKE_PREFIX_PATH "${_pixi}")
      set(_qkind "pixi")
    else()
      set(_qkind "system")
      list(REMOVE_ITEM CMAKE_PREFIX_PATH "${_pixi}") # 反污染：SYSTEM 态剔除 pixi 前缀
    endif()
    find_package(Qt6 COMPONENTS Widgets QUIET)
    if(NOT Qt6_FOUND)
      message(FATAL_ERROR "强制 ${VISIAENGINE_QT_SDK} 的 Qt6 未找到（该模式不回落；改 AUTO 或给目录）")
    endif()
    if(_qkind STREQUAL "system" AND Qt6_FOUND AND Qt6_DIR MATCHES "\.pixi|envs/")
      message(FATAL_ERROR "SYSTEM 模式拒收 pixi 树内 Qt6（${Qt6_DIR}）；改 AUTO/PIXI 或开未激活 shell")
    endif()
  else()
    if(NOT IS_DIRECTORY "${VISIAENGINE_QT_SDK}")
      message(FATAL_ERROR "VISIAENGINE_QT_SDK=${VISIAENGINE_QT_SDK} 不是目录（显式路径=逃生舱）")
    endif()
    list(APPEND CMAKE_PREFIX_PATH "${VISIAENGINE_QT_SDK}")
    find_package(Qt6 COMPONENTS Widgets QUIET)
    if(NOT Qt6_FOUND)
      message(FATAL_ERROR "目录 ${VISIAENGINE_QT_SDK} 下无 Qt6Config（逃生舱路径亦须真实）")
    endif()
    set(_qkind "path")
  endif()
  if(_qkind STREQUAL "system")
    message(STATUS "Qt: ${Qt6_VERSION} [system] ${Qt6_DIR}")
  elseif(_qkind)
    message(STATUS "Qt: ${Qt6_VERSION} [${_qkind}] ${Qt6_DIR}")
  endif()
  set(VISIAENGINE_QT_KIND "${_qkind}" PARENT_SCOPE)
endfunction()
